# Site settings
title: GrooveNiño
description: 'musik håndværker'
url: 'http://groovenino.com'
baseurl: '/'
# google_analytics: 'UA-10305375'
# disqus_shortname: ''

author:
  name: 'Grooveniño'
  email: oscar@groovenino.com
  twitter_username: groovenino
  facebook_username: groovenino
  soundcloud_username: groovenino

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
